services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - rabbitmq
    volumes:
      - ./data:/usr/src/app/data
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"